import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Jacket Men`s",
    price: "3000",
    image: "/images/jacket-2.jpg",
    categoryName: "Men",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: " Men`s",
    price: "3000",
    image: "/images/jacket-2.jpg",
    categoryName: "Men",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Jacket Men`s",
    price: "4000",
    image: "/images/jacket-2.jpg",
    categoryName: "Men",
    rating: 2,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Jacket Men`s",
    price: "2000",
    image: "/images/jacket-2.jpg",
    categoryName: "Men",
    rating: 5,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Dress Women`s",
    price: "2000",
    image: "/images/women-dress-1.jpg",
    categoryName: "Women",
    rating: 3,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Dress Women`s",
    price: "2500",
    image: "/images/women-dress-1.jpg",
    categoryName: "Women",
    rating: 2,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Dress Women`s",
    price: "4000",
    image: "/images/women-dress-1.jpg",
    categoryName: "Women",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Kids Costume",
    price: "1500",
    image: "/images/kid-dress.jpg",
    categoryName: "Kids",
    rating: 3,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Kids Costume",
    price: "2500",
    image: "/images/kid-dress.jpg",
    categoryName: "Kids",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Kids Costume",
    price: "500",
    image: "/images/kid-dress.jpg",
    categoryName: "Kids",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Kids Costume",
    price: "500",
    image: "/images/kid-dress.jpg",
    categoryName: "Kids",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "Kids Costume",
    price: "500",
    image: "/images/kid-dress.jpg",
    categoryName: "Kids",
    rating: 4,
    isWished: false,
  },
  {
    _id: uuid(),
    title: "art Costume",
    price: "5000",
    image: "/images/kid-dress.jpg",
    categoryName: "Kids",
    rating: 4,
    isWished: false,
  },
];
